// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSCOQXULAeoDP4jWbNa59ss_7hv-nSquE',
    appId: '1:516556205461:web:a70d981db2c43ce1f25a9c',
    messagingSenderId: '516556205461',
    projectId: 'fibre-bd-com-e7486',
    authDomain: 'fibre-bd-com-e7486.firebaseapp.com',
    storageBucket: 'fibre-bd-com-e7486.appspot.com',
    measurementId: 'G-ML5JW3DFCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHU6MGS9SvHM81CcLnapEP3DMR2ZEIHiE',
    appId: '1:516556205461:android:802d92370df85566f25a9c',
    messagingSenderId: '516556205461',
    projectId: 'fibre-bd-com-e7486',
    storageBucket: 'fibre-bd-com-e7486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtEI07jNrYgMNoGoHNWbQz97OnfNWyySY',
    appId: '1:516556205461:ios:70401a80dd778013f25a9c',
    messagingSenderId: '516556205461',
    projectId: 'fibre-bd-com-e7486',
    storageBucket: 'fibre-bd-com-e7486.appspot.com',
    iosClientId: '516556205461-8t1ebcda58shgipn9doe88quhtgf3jp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fibreCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtEI07jNrYgMNoGoHNWbQz97OnfNWyySY',
    appId: '1:516556205461:ios:70401a80dd778013f25a9c',
    messagingSenderId: '516556205461',
    projectId: 'fibre-bd-com-e7486',
    storageBucket: 'fibre-bd-com-e7486.appspot.com',
    iosClientId: '516556205461-8t1ebcda58shgipn9doe88quhtgf3jp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fibreCom',
  );
}
